Feature/s44 jade2716 todd
bcgov/jpss-jade-ccm pull request #141
Opened 2023-11-09 21:20 UTC by twuolleparcsystems

2023-11-20 20:16 UTC, elainecwong requested changes

2023-11-20 20:16 UTC, elainecwong commented on src/main/java/ccm/CcmDemsAdapter.java
The DEMS Adapter does not compile.
For the new Http calls, instead of copying the exact code from the existing methods, try to re-use the existing call, by referencing it (i.e. http_syncCaseUserList calls syncCaseUserList)

There is already an http equivalent of getCourtCaseStatusByKeyHttp in the form of getCourtCaseStatusExists()

2023-11-21 21:52 UTC, twuolleparcsystems commented on src/main/java/ccm/CcmDemsAdapter.java
Weird merging thing with DemsAdapter. Methods re-vamped to allow http

2023-11-21 21:53 UTC, twuolleparcsystems commented on src/main/java/ccm/CcmReportsProcessor.java
added  the exception handler

2023-11-28 20:49 UTC, elainecwong requested changes

2023-11-28 20:49 UTC, elainecwong commented on src/main/java/ccm/CcmDemsAdapter.java
Code still does not deploy properly. checkIncrementRecordDocIdHttp has missing / in the "from" call.

2023-11-28 20:49 UTC, elainecwong commented on src/main/java/ccm/CcmReportsProcessor.java
When trying to process a report event, errors occur.

[2] 2023-11-28 12:15:08,645 WARN  [org.apa.cam.com.kaf.KafkaConsumer] (Camel (camel-1) thread #1 - KafkaConsumer[ccm-reports]) Error during processing. Exchange[0A43B16B8630269-0000000000000006]. Caused by: [org.apache.camel.InvalidPayloadException - No body available of type: java.io.InputStream but has type: java.util.LinkedHashMap on: Message. Caused by: No type converter available to convert from type: java.util.LinkedHashMap to the required type: java.io.InputStream. Exchange[0A43B16B8630269-0000000000000007]. Caused by: [org.apache.camel.NoTypeConversionAvailableException - No type converter available to convert from type: java.util.LinkedHashMap to the required type: java.io.InputStream]]: org.apache.camel.InvalidPayloadException: No body available of type: java.io.InputStream but has type: java.util.LinkedHashMap on: Message. Caused by: No type converter available to convert from type: java.util.LinkedHashMap to the required type: java.io.InputStream. Exchange[0A43B16B8630269-0000000000000007]. Caused by: [org.apache.camel.NoTypeConversionAvailableException - No type converter available to convert from type: java.util.LinkedHashMap to the required type: java.io.InputStream]
[2]     at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:125)
[2]     at org.apache.camel.component.http.HttpProducer.createRequestEntity(HttpProducer.java:745)
[2]     at org.apache.camel.component.http.HttpProducer.createMethod(HttpProducer.java:632)
[2]     at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:162)
[2]     at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66)
[2]     at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
[2]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:818)
[2]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:726)
[2]     at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:189)
[2]     at org.apache.camel.impl.engine.DefaultReactiveExecutor.schedule(DefaultReactiveExecutor.java:56)
[2]     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.lambda$doRun$1(RedeliveryErrorHandler.java:823)
[2]     at org.apache.camel.component.kafka.producer.support.KafkaProducerCallBack.doContinueRouting(KafkaProducerCallBack.java:95)
[2]     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2]     at java.base/java.lang.Thread.run(Thread.java:829)
[2] Caused by: org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.util.LinkedHashMap to the required type: java.io.InputStream
[2]     at org.apache.camel.impl.converter.CoreTypeConverterRegistry.mandatoryConvertTo(CoreTypeConverterRegistry.java:274)
[2]     at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:123)
[2]     ... 16 more
[2]

2024-02-23 00:06 UTC, closed without merging